steps
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/project-demo-376608/nginx:v1", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/project-demo-376608/nginx:v1"]
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=GKE/
  - --image=gcr.io/project-demo-376608/nginx:v1
  - --location=us-central1
  - --cluster=my-first-demo1
