---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
   name:nginx
    app: nginx-1
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-1
  type: LoadBalancer
